# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0019_auto_20181003_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_notes', models.FileField(blank=True, max_length=4000, upload_to='media/TutorNotes')),
                ('tut_notes_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Tutor')),
            ],
        ),
    ]
