# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0019_auto_20181003_0519'),
        ('tutor', '0002_remove_tutornotes_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutornotes',
            name='note_belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log.Tutor'),
            preserve_default=False,
        ),
    ]
