# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutornotes_note_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutornotes',
            old_name='note_belongs_to',
            new_name='tutor',
        ),
    ]
