# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20181003_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutornotes',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
