# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_advertisements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Advertisements',
        ),
    ]
