# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_auto_20181005_0649'),
        ('tutor', '0007_auto_20181005_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('ad_pic', models.ImageField(upload_to='media/Advertisements')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Tutor')),
            ],
        ),
    ]
