# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
