# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adt_title', models.CharField(max_length=25)),
                ('adt_desc', models.IntegerField()),
                ('adt_pic', models.ImageField(upload_to='media/ads')),
            ],
        ),
    ]
