# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='adt_desc',
            new_name='ad_desc',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='adt_title',
            new_name='ad_title',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='adt_pic',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_pic',
            field=models.ImageField(blank=True, upload_to='media/ads'),
        ),
    ]
