# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_auto_20181006_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_desc',
            field=models.CharField(max_length=200),
        ),
    ]
