# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_advertisement_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutornotes',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
