# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pdtcustmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('cpdt_id', models.IntegerField()),
                ('cus_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_id', models.IntegerField(default=None, null=True)),
                ('pdt_name', models.CharField(max_length=25)),
                ('pdt_rate', models.IntegerField()),
                ('pdt_rel1', models.IntegerField(null=True)),
                ('pdt_pic', models.ImageField(upload_to='media/pdtpics')),
                ('pdt_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_locality', models.CharField(max_length=255)),
                ('user_type', models.IntegerField()),
                ('stud_pic', models.ImageField(blank=True, upload_to='media/studentpics')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_locality', models.CharField(max_length=255)),
                ('tut_rate', models.IntegerField()),
                ('tut_rating', models.IntegerField(null=True)),
                ('tut_type', models.CharField(choices=[('freelance', 'Freelance Tutor'), ('comp', 'Company')], max_length=15)),
                ('tut_pic', models.ImageField(blank=True, upload_to='media/tutorpics')),
                ('user_type', models.IntegerField()),
                ('tut_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Category')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
