# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log.Category'),
            preserve_default=False,
        ),
    ]
