# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_student_stud_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
