# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20180928_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_course',
            field=models.ForeignKey(default='choose', on_delete=django.db.models.deletion.CASCADE, to='log.Category'),
        ),
    ]
