# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20180928_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Category'),
        ),
    ]
