# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20180928_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tut_course',
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_course',
            field=models.ManyToManyField(to='log.Category'),
        ),
    ]
