# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20180928_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_course',
            field=models.ManyToManyField(related_name='subject', to='log.Category'),
        ),
    ]
