# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20180928_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_downvotes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_upvotes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
