# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20180929_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_rating',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
