# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20181001_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
