# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_auto_20181001_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
