# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_tutor_tut_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_notes',
            field=models.FileField(blank=True, max_length=4000, upload_to='media/TutorNotes'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_notes_type',
            field=models.CharField(choices=[('freelance', 'Freelance Tutor'), ('company', 'Company')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_type',
            field=models.CharField(choices=[('freelance', 'Freelance Tutor'), ('company', 'Company')], max_length=15),
        ),
    ]
