# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_auto_20181003_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tut_notes',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tut_notes_type',
        ),
    ]
