# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0019_auto_20181003_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudTutmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='pdtcustmap',
        ),
    ]
