# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_auto_20181005_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_pic',
            field=models.ImageField(blank=True, default='static/unk.png', null=True, upload_to='media/tutorpics'),
        ),
    ]
