# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_auto_20181006_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
