# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0026_auto_20181006_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
