# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_auto_20181006_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='log.Category'),
        ),
    ]
