# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0013_auto_20180928_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ManyToManyField(to='log.Tutor')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
